# coding: utf-8

"""
    FormKiQ HTTP API

    Formkiq API: Document Management Platform API using JWT Authentication  # noqa: E501

    The version of the OpenAPI document: 1.12.0
    Contact: support@formkiq.com
    Generated by: https://openapi-generator.tech
"""

from formkiq_client.paths.folders.post import AddFolder
from formkiq_client.paths.folders_index_key.delete import DeleteFolder
from formkiq_client.paths.folders.get import GetFolderDocuments


class FoldersApi(
    AddFolder,
    DeleteFolder,
    GetFolderDocuments,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
