# coding: utf-8

"""
    FormKiQ HTTP API

    Formkiq API: Document Management Platform API using JWT Authentication  # noqa: E501

    The version of the OpenAPI document: 1.12.0
    Contact: support@formkiq.com
    Generated by: https://openapi-generator.tech
"""

from formkiq_client.paths.public_documents.post import PublicAddDocument
from formkiq_client.paths.public_webhooks_webhooks.post import PublicAddWebhook


class PublicApi(
    PublicAddDocument,
    PublicAddWebhook,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
