# coding: utf-8

"""
    FormKiQ API JWT

    FormKiQ API: Document Management Platform API using OAuth(JWT) Authentication  You can find out more about FormKiQ at [https://formkiq.com](http://formkiq.com).  ## Introduction  FormKiQ is an API-first (head-less), battle-tested document management API. The FormKiQ API provides all the API endpoints to build your Perfect Document Management Platform.  FormKiQ API was built on top of [OpenAPI specification](https://www.openapis.org), so it is easy to use the API spec file with any application that supports the OpenAPI specification.  Open API OAuth Specification - https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-jwt.yaml  Open API IAM Specification - https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-iam.yaml  ## Authentication FormKiQ offers three forms of authentication:   - OAuth(JWT)   - AWS IAM   - API Key

    The version of the OpenAPI document: 1.19.1
    Contact: support@formkiq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formkiq_client.models.generate_document_attribute_value_response import GenerateDocumentAttributeValueResponse

class TestGenerateDocumentAttributeValueResponse(unittest.TestCase):
    """GenerateDocumentAttributeValueResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenerateDocumentAttributeValueResponse:
        """Test GenerateDocumentAttributeValueResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenerateDocumentAttributeValueResponse`
        """
        model = GenerateDocumentAttributeValueResponse()
        if include_optional:
            return GenerateDocumentAttributeValueResponse(
                attribute = formkiq_client.models.document_attribute.DocumentAttribute(
                    key = '', 
                    string_value = '', 
                    string_values = [
                        ''
                        ], 
                    number_value = 1.337, 
                    number_values = [
                        1.337
                        ], 
                    boolean_value = True, 
                    date_value = '', 
                    date_values = [
                        ''
                        ], 
                    inserted_date = '', 
                    user_id = '', 
                    value_type = 'BOOLEAN', 
                    entity = formkiq_client.models.entity.Entity(
                        entity_id = '', 
                        entity_type_id = '', 
                        name = '', 
                        inserted_date = '', 
                        attributes = [
                            formkiq_client.models.entity_attribute.EntityAttribute(
                                key = '', 
                                string_value = '', 
                                number_value = 1.337, 
                                boolean_value = True, 
                                date_value = '', )
                            ], ), 
                    entities = [
                        formkiq_client.models.entity.Entity(
                            entity_id = '', 
                            entity_type_id = '', 
                            name = '', 
                            inserted_date = '', )
                        ], ),
                sequence = 1,
                period = '2026'
            )
        else:
            return GenerateDocumentAttributeValueResponse(
                attribute = formkiq_client.models.document_attribute.DocumentAttribute(
                    key = '', 
                    string_value = '', 
                    string_values = [
                        ''
                        ], 
                    number_value = 1.337, 
                    number_values = [
                        1.337
                        ], 
                    boolean_value = True, 
                    date_value = '', 
                    date_values = [
                        ''
                        ], 
                    inserted_date = '', 
                    user_id = '', 
                    value_type = 'BOOLEAN', 
                    entity = formkiq_client.models.entity.Entity(
                        entity_id = '', 
                        entity_type_id = '', 
                        name = '', 
                        inserted_date = '', 
                        attributes = [
                            formkiq_client.models.entity_attribute.EntityAttribute(
                                key = '', 
                                string_value = '', 
                                number_value = 1.337, 
                                boolean_value = True, 
                                date_value = '', )
                            ], ), 
                    entities = [
                        formkiq_client.models.entity.Entity(
                            entity_id = '', 
                            entity_type_id = '', 
                            name = '', 
                            inserted_date = '', )
                        ], ),
                sequence = 1,
                period = '2026',
        )
        """

    def testGenerateDocumentAttributeValueResponse(self):
        """Test GenerateDocumentAttributeValueResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
