# coding: utf-8

"""
    FormKiQ API JWT

    Formkiq API: Document Management Platform API using OAuth(JWT) Authentication  You can find out more about FormKiQ at [https://formkiq.com](http://formkiq.com).  ## Introduction  FormKiQ is an API-first (head-less), battle-tested document management API. The FormKiQ API provides all the API endpoints to build your Perfect Document Management Platform.  FormKiQ API was built on top of [OpenAPI specification](https://www.openapis.org), so it is easy to use the API spec file with any application that supports the OpenAPI specification.  Open API OAuth Specification - https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-jwt.yaml  Open API IAM Specification - https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-iam.yaml  ## Authentication FormKiQ offers three forms of authentication:   - OAuth(JWT)   - AWS IAM   - API Key

    The version of the OpenAPI document: 1.18.0
    Contact: support@formkiq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.attributes_api import AttributesApi


class TestAttributesApi(unittest.TestCase):
    """AttributesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AttributesApi()

    def tearDown(self) -> None:
        pass

    def test_add_attribute(self) -> None:
        """Test case for add_attribute

        Add new attribute
        """
        pass

    def test_delete_attribute(self) -> None:
        """Test case for delete_attribute

        Delete attribute
        """
        pass

    def test_get_attribute(self) -> None:
        """Test case for get_attribute

        Get Attribute
        """
        pass

    def test_get_attribute_allowed_values(self) -> None:
        """Test case for get_attribute_allowed_values

        Get Attribute Allowed Values
        """
        pass

    def test_get_attributes(self) -> None:
        """Test case for get_attributes

        Get Attributes listing
        """
        pass

    def test_update_attribute(self) -> None:
        """Test case for update_attribute

        Update existing attribute
        """
        pass


if __name__ == '__main__':
    unittest.main()
