# coding: utf-8

"""
    FormKiQ API JWT

    Formkiq API: Document Management Platform API using OAuth(JWT) Authentication  You can find out more about FormKiQ at [https://formkiq.com](http://formkiq.com).  ## Introduction  FormKiQ is an API-first (head-less), battle-tested document management API. The FormKiQ API provides all the API endpoints to build your Perfect Document Management Platform.  FormKiQ API was built on top of [OpenAPI specification](https://www.openapis.org), so it is easy to use the API spec file with any application that supports the OpenAPI specification.  Open API OAuth Specification - https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-jwt.yaml  Open API IAM Specification - https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-iam.yaml  ## Authentication FormKiQ offers three forms of authentication:   - OAuth(JWT)   - AWS IAM   - API Key

    The version of the OpenAPI document: 1.18.0
    Contact: support@formkiq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.model.open_search_snapshot import OpenSearchSnapshot

class TestOpenSearchSnapshot(unittest.TestCase):
    """OpenSearchSnapshot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenSearchSnapshot:
        """Test OpenSearchSnapshot
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenSearchSnapshot`
        """
        model = OpenSearchSnapshot()
        if include_optional:
            return OpenSearchSnapshot(
                snapshot = '',
                uuid = '',
                version = '',
                indices = [
                    ''
                    ],
                shards = openapi_client.models.open_search_snapshot_shard.OpenSearchSnapshotShard(
                    total = 1.337, 
                    failed = 1.337, 
                    successful = 1.337, ),
                failures = [
                    openapi_client.models.open_search_snapshot_failure.OpenSearchSnapshotFailure(
                        index = '', 
                        index_uuid = '', 
                        shard_id = 56, 
                        reason = '', 
                        node_id = '', 
                        status = '', )
                    ],
                state = '',
                start_time = '',
                start_time_in_millis = 1.337,
                end_time = '',
                end_time_in_millis = 1.337,
                duration_in_millis = 1.337
            )
        else:
            return OpenSearchSnapshot(
        )
        """

    def testOpenSearchSnapshot(self):
        """Test OpenSearchSnapshot"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
