# coding: utf-8

"""
    FormKiQ API JWT

    FormKiQ API: Document Management Platform API using OAuth(JWT) Authentication  You can find out more about FormKiQ at [https://formkiq.com](http://formkiq.com).  ## Introduction  FormKiQ is an API-first (head-less), battle-tested document management API. The FormKiQ API provides all the API endpoints to build your Perfect Document Management Platform.  FormKiQ API was built on top of [OpenAPI specification](https://www.openapis.org), so it is easy to use the API spec file with any application that supports the OpenAPI specification.  Open API OAuth Specification - https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-jwt.yaml  Open API IAM Specification - https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-iam.yaml  ## Authentication FormKiQ offers three forms of authentication:   - OAuth(JWT)   - AWS IAM   - API Key

    The version of the OpenAPI document: 1.19.0
    Contact: support@formkiq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from formkiq_client.models.activity_delegation import ActivityDelegation
from formkiq_client.models.activity_status import ActivityStatus
from formkiq_client.models.user_activity_changes import UserActivityChanges
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Activity(BaseModel):
    """
    Activity
    """ # noqa: E501
    resource: Optional[StrictStr] = Field(default=None, description="Resource of Activity")
    type: Optional[StrictStr] = Field(default=None, description="Type of Activity")
    source: Optional[StrictStr] = Field(default=None, description="The Source of the activity")
    source_ip_address: Optional[StrictStr] = Field(default=None, description="The Source IP address of the user", alias="sourceIpAddress")
    message: Optional[StrictStr] = Field(default=None, description="The activity message")
    status: Optional[ActivityStatus] = None
    inserted_date: Optional[StrictStr] = Field(default=None, description="Inserted Timestamp", alias="insertedDate")
    user_id: Optional[StrictStr] = Field(default=None, description="User who added document", alias="userId")
    delegation: Optional[ActivityDelegation] = None
    document_id: Optional[Any] = Field(default=None, description="Document Identifier", alias="documentId")
    artifact_id: Optional[Any] = Field(default=None, description="Document Artifact Identifier", alias="artifactId")
    attribute_key: Optional[Any] = Field(default=None, description="Document Attribute Key", alias="attributeKey")
    entity_type_id: Optional[StrictStr] = Field(default=None, description="Entity Type Identifier", alias="entityTypeId")
    entity_id: Optional[StrictStr] = Field(default=None, description="Entity Identifier", alias="entityId")
    api_key: Optional[StrictStr] = Field(default=None, description="API Key", alias="apiKey")
    ruleset_id: Optional[StrictStr] = Field(default=None, description="Ruleset Identifier", alias="rulesetId")
    var_schema: Optional[StrictStr] = Field(default=None, description="Schema Identifier", alias="schema")
    mapping_id: Optional[StrictStr] = Field(default=None, description="Mapping Identifier", alias="mappingId")
    classification_id: Optional[StrictStr] = Field(default=None, description="Classification Identifier", alias="classificationId")
    rule_id: Optional[StrictStr] = Field(default=None, description="Ruleset Rule Identifier", alias="ruleId")
    workflow_id: Optional[StrictStr] = Field(default=None, description="Workflow Identifier", alias="workflowId")
    queue_id: Optional[StrictStr] = Field(default=None, description="Queue Identifier", alias="queueId")
    webhook_id: Optional[StrictStr] = Field(default=None, description="Webhook Identifier", alias="webhookId")
    locale: Optional[StrictStr] = Field(default=None, description="Locale Identifier")
    control_policy: Optional[StrictStr] = Field(default=None, description="Control Policy Type", alias="controlPolicy")
    changes: Optional[Dict[str, UserActivityChanges]] = None
    __properties: ClassVar[List[str]] = ["resource", "type", "source", "sourceIpAddress", "message", "status", "insertedDate", "userId", "delegation", "documentId", "artifactId", "attributeKey", "entityTypeId", "entityId", "apiKey", "rulesetId", "schema", "mappingId", "classificationId", "ruleId", "workflowId", "queueId", "webhookId", "locale", "controlPolicy", "changes"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Activity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of delegation
        if self.delegation:
            _dict['delegation'] = self.delegation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in changes (dict)
        _field_dict = {}
        if self.changes:
            for _key_changes in self.changes:
                if self.changes[_key_changes]:
                    _field_dict[_key_changes] = self.changes[_key_changes].to_dict()
            _dict['changes'] = _field_dict
        # set to None if document_id (nullable) is None
        # and model_fields_set contains the field
        if self.document_id is None and "document_id" in self.model_fields_set:
            _dict['documentId'] = None

        # set to None if artifact_id (nullable) is None
        # and model_fields_set contains the field
        if self.artifact_id is None and "artifact_id" in self.model_fields_set:
            _dict['artifactId'] = None

        # set to None if attribute_key (nullable) is None
        # and model_fields_set contains the field
        if self.attribute_key is None and "attribute_key" in self.model_fields_set:
            _dict['attributeKey'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Activity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "resource": obj.get("resource"),
            "type": obj.get("type"),
            "source": obj.get("source"),
            "sourceIpAddress": obj.get("sourceIpAddress"),
            "message": obj.get("message"),
            "status": obj.get("status"),
            "insertedDate": obj.get("insertedDate"),
            "userId": obj.get("userId"),
            "delegation": ActivityDelegation.from_dict(obj["delegation"]) if obj.get("delegation") is not None else None,
            "documentId": obj.get("documentId"),
            "artifactId": obj.get("artifactId"),
            "attributeKey": obj.get("attributeKey"),
            "entityTypeId": obj.get("entityTypeId"),
            "entityId": obj.get("entityId"),
            "apiKey": obj.get("apiKey"),
            "rulesetId": obj.get("rulesetId"),
            "schema": obj.get("schema"),
            "mappingId": obj.get("mappingId"),
            "classificationId": obj.get("classificationId"),
            "ruleId": obj.get("ruleId"),
            "workflowId": obj.get("workflowId"),
            "queueId": obj.get("queueId"),
            "webhookId": obj.get("webhookId"),
            "locale": obj.get("locale"),
            "controlPolicy": obj.get("controlPolicy"),
            "changes": dict(
                (_k, UserActivityChanges.from_dict(_v))
                for _k, _v in obj["changes"].items()
            )
            if obj.get("changes") is not None
            else None
        })
        return _obj


