# coding: utf-8

"""
    FormKiQ API JWT

    FormKiQ API: Document Management Platform API using OAuth(JWT) Authentication  You can find out more about FormKiQ at [https://formkiq.com](http://formkiq.com).  ## Introduction  FormKiQ is an API-first (head-less), battle-tested document management API. The FormKiQ API provides all the API endpoints to build your Perfect Document Management Platform.  FormKiQ API was built on top of [OpenAPI specification](https://www.openapis.org), so it is easy to use the API spec file with any application that supports the OpenAPI specification.  Open API OAuth Specification - https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-jwt.yaml  Open API IAM Specification - https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-iam.yaml  ## Authentication FormKiQ offers three forms of authentication:   - OAuth(JWT)   - AWS IAM   - API Key

    The version of the OpenAPI document: 1.19.0
    Contact: support@formkiq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from formkiq_client.models.add_action import AddAction
from formkiq_client.models.add_workflow_step_decision import AddWorkflowStepDecision
from formkiq_client.models.add_workflow_step_queue import AddWorkflowStepQueue
from formkiq_client.models.workflow_step_decision import WorkflowStepDecision
from formkiq_client.models.workflow_step_mapping import WorkflowStepMapping
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AddWorkflowStep(BaseModel):
    """
    AddWorkflowStep
    """ # noqa: E501
    step_id: Optional[StrictStr] = Field(default=None, description="Workflow Step Identifier", alias="stepId")
    description: Optional[StrictStr] = Field(default=None, description="Workflow Step description")
    action: Optional[AddAction] = None
    queue: Optional[AddWorkflowStepQueue] = None
    mappings: Optional[List[WorkflowStepMapping]] = None
    decision: Optional[WorkflowStepDecision] = None
    decisions: Optional[List[AddWorkflowStepDecision]] = Field(default=None, description="Deprecated; use 'decision' instead")
    __properties: ClassVar[List[str]] = ["stepId", "description", "action", "queue", "mappings", "decision", "decisions"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AddWorkflowStep from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of action
        if self.action:
            _dict['action'] = self.action.to_dict()
        # override the default output from pydantic by calling `to_dict()` of queue
        if self.queue:
            _dict['queue'] = self.queue.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in mappings (list)
        _items = []
        if self.mappings:
            for _item_mappings in self.mappings:
                if _item_mappings:
                    _items.append(_item_mappings.to_dict())
            _dict['mappings'] = _items
        # override the default output from pydantic by calling `to_dict()` of decision
        if self.decision:
            _dict['decision'] = self.decision.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in decisions (list)
        _items = []
        if self.decisions:
            for _item_decisions in self.decisions:
                if _item_decisions:
                    _items.append(_item_decisions.to_dict())
            _dict['decisions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AddWorkflowStep from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "stepId": obj.get("stepId"),
            "description": obj.get("description"),
            "action": AddAction.from_dict(obj["action"]) if obj.get("action") is not None else None,
            "queue": AddWorkflowStepQueue.from_dict(obj["queue"]) if obj.get("queue") is not None else None,
            "mappings": [WorkflowStepMapping.from_dict(_item) for _item in obj["mappings"]] if obj.get("mappings") is not None else None,
            "decision": WorkflowStepDecision.from_dict(obj["decision"]) if obj.get("decision") is not None else None,
            "decisions": [AddWorkflowStepDecision.from_dict(_item) for _item in obj["decisions"]] if obj.get("decisions") is not None else None
        })
        return _obj


