# coding: utf-8

"""
    FormKiQ API JWT

    FormKiQ API: Document Management Platform API using OAuth(JWT) Authentication  You can find out more about FormKiQ at [https://formkiq.com](http://formkiq.com).  ## Introduction  FormKiQ is an API-first (head-less), battle-tested document management API. The FormKiQ API provides all the API endpoints to build your Perfect Document Management Platform.  FormKiQ API was built on top of [OpenAPI specification](https://www.openapis.org), so it is easy to use the API spec file with any application that supports the OpenAPI specification.  Open API OAuth Specification - https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-jwt.yaml  Open API IAM Specification - https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-iam.yaml  ## Authentication FormKiQ offers three forms of authentication:   - OAuth(JWT)   - AWS IAM   - API Key

    The version of the OpenAPI document: 1.19.1
    Contact: support@formkiq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from formkiq_client.models.docusign_reminder_recipient import DocusignReminderRecipient
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AddDocusignEnvelopeRemindersResponse(BaseModel):
    """
    For targeted reminders, recipients contains exactly one outcome for each requested recipient ID. HTTP 200 can include accepted and failed outcomes, including when every recipient failed at the provider after validation. Invalid selections detected before the resend return 400 instead. Envelope-wide acceptance returns an empty object; do not infer individual outcomes. There is no overall status field. Authentication, validation, rate-limit, upstream, and timeout errors use the documented 4xx/5xx responses.
    """ # noqa: E501
    recipients: Optional[Annotated[List[DocusignReminderRecipient], Field(min_length=1)]] = Field(default=None, description="Outcomes for the selected recipients, present for targeted requests and omitted for envelope-wide reminders. A timeout or missing provider outcome must not be represented as confirmed acceptance or failure.")
    __properties: ClassVar[List[str]] = ["recipients"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AddDocusignEnvelopeRemindersResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in recipients (list)
        _items = []
        if self.recipients:
            for _item_recipients in self.recipients:
                _items.append(_item_recipients.to_dict() if _item_recipients is not None else None)
            _dict['recipients'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AddDocusignEnvelopeRemindersResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "recipients": [DocusignReminderRecipient.from_dict(_item) for _item in obj["recipients"]] if obj.get("recipients") is not None else None
        })
        return _obj


