# coding: utf-8

"""
    FormKiQ API JWT

    FormKiQ API: Document Management Platform API using OAuth(JWT) Authentication  You can find out more about FormKiQ at [https://formkiq.com](http://formkiq.com).  ## Introduction  FormKiQ is an API-first (head-less), battle-tested document management API. The FormKiQ API provides all the API endpoints to build your Perfect Document Management Platform.  FormKiQ API was built on top of [OpenAPI specification](https://www.openapis.org), so it is easy to use the API spec file with any application that supports the OpenAPI specification.  Open API OAuth Specification - https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-jwt.yaml  Open API IAM Specification - https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-iam.yaml  ## Authentication FormKiQ offers three forms of authentication:   - OAuth(JWT)   - AWS IAM   - API Key

    The version of the OpenAPI document: 1.19.1
    Contact: support@formkiq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DocumentNotificationStatus(str, Enum):
    """
    Status of the document notification. WAITING awaits an external trigger and is not eligible for processing. PENDING is ready for processing. ACTION_CREATED indicates that a Document Action has been created.
    """

    """
    allowed enum values
    """
    WAITING = 'WAITING'
    PENDING = 'PENDING'
    ACTION_CREATED = 'ACTION_CREATED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DocumentNotificationStatus from a JSON string"""
        return cls(json.loads(json_str))


