# coding: utf-8

"""
    FormKiQ API JWT

    FormKiQ API: Document Management Platform API using OAuth(JWT) Authentication  You can find out more about FormKiQ at [https://formkiq.com](http://formkiq.com).  ## Introduction  FormKiQ is an API-first (head-less), battle-tested document management API. The FormKiQ API provides all the API endpoints to build your Perfect Document Management Platform.  FormKiQ API was built on top of [OpenAPI specification](https://www.openapis.org), so it is easy to use the API spec file with any application that supports the OpenAPI specification.  Open API OAuth Specification - https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-jwt.yaml  Open API IAM Specification - https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-iam.yaml  ## Authentication FormKiQ offers three forms of authentication:   - OAuth(JWT)   - AWS IAM   - API Key

    The version of the OpenAPI document: 1.19.1
    Contact: support@formkiq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from formkiq_client.models.docusign_envelope_recipients import DocusignEnvelopeRecipients
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetDocusignEnvelopeResponse(BaseModel):
    """
    The DocuSign Get Envelope response with include=recipients, returned without enrichment. Additional DocuSign fields are preserved. Optional fields are returned only when supplied by DocuSign. A completed envelope does not confirm that FormKiQ has stored the signed PDF.
    """ # noqa: E501
    envelope_id: Optional[StrictStr] = Field(default=None, description="DocuSign envelope identifier", alias="envelopeId")
    status: Optional[StrictStr] = Field(default=None, description="Envelope status reported by DocuSign, such as created, sent, delivered, signed, completed, declined, or voided.")
    status_changed_date_time: Optional[datetime] = Field(default=None, description="Time DocuSign reports the envelope status changed", alias="statusChangedDateTime")
    sent_date_time: Optional[datetime] = Field(default=None, alias="sentDateTime")
    delivered_date_time: Optional[datetime] = Field(default=None, alias="deliveredDateTime")
    completed_date_time: Optional[datetime] = Field(default=None, alias="completedDateTime")
    declined_date_time: Optional[datetime] = Field(default=None, alias="declinedDateTime")
    voided_date_time: Optional[datetime] = Field(default=None, alias="voidedDateTime")
    recipients: Optional[DocusignEnvelopeRecipients] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["envelopeId", "status", "statusChangedDateTime", "sentDateTime", "deliveredDateTime", "completedDateTime", "declinedDateTime", "voidedDateTime", "recipients"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetDocusignEnvelopeResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of recipients
        if self.recipients:
            _dict['recipients'] = self.recipients.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetDocusignEnvelopeResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "envelopeId": obj.get("envelopeId"),
            "status": obj.get("status"),
            "statusChangedDateTime": obj.get("statusChangedDateTime"),
            "sentDateTime": obj.get("sentDateTime"),
            "deliveredDateTime": obj.get("deliveredDateTime"),
            "completedDateTime": obj.get("completedDateTime"),
            "declinedDateTime": obj.get("declinedDateTime"),
            "voidedDateTime": obj.get("voidedDateTime"),
            "recipients": DocusignEnvelopeRecipients.from_dict(obj["recipients"]) if obj.get("recipients") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


