# coding: utf-8

"""
    FormKiQ API JWT

    FormKiQ API: Document Management Platform API using OAuth(JWT) Authentication  You can find out more about FormKiQ at [https://formkiq.com](http://formkiq.com).  ## Introduction  FormKiQ is an API-first (head-less), battle-tested document management API. The FormKiQ API provides all the API endpoints to build your Perfect Document Management Platform.  FormKiQ API was built on top of [OpenAPI specification](https://www.openapis.org), so it is easy to use the API spec file with any application that supports the OpenAPI specification.  Open API OAuth Specification - https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-jwt.yaml  Open API IAM Specification - https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-iam.yaml  ## Authentication FormKiQ offers three forms of authentication:   - OAuth(JWT)   - AWS IAM   - API Key

    The version of the OpenAPI document: 1.19.0
    Contact: support@formkiq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from formkiq_client.models.site_config import SiteConfig
from formkiq_client.models.site_group_permissions import SiteGroupPermissions
from formkiq_client.models.site_permission import SitePermission
from formkiq_client.models.site_status import SiteStatus
from formkiq_client.models.site_usage import SiteUsage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Site(BaseModel):
    """
    Site
    """ # noqa: E501
    site_id: Optional[StrictStr] = Field(default=None, description="Site Identifier", alias="siteId")
    title: Optional[StrictStr] = Field(default=None, description="Site Title")
    status: Optional[SiteStatus] = None
    permission: Optional[SitePermission] = None
    roles: Optional[List[StrictStr]] = Field(default=None, description="List of roles used to get permissions")
    permissions: Optional[List[SiteGroupPermissions]] = None
    upload_email: Optional[StrictStr] = Field(default=None, description="SiteId document upload email address", alias="uploadEmail")
    config: Optional[SiteConfig] = None
    usage: Optional[SiteUsage] = None
    __properties: ClassVar[List[str]] = ["siteId", "title", "status", "permission", "roles", "permissions", "uploadEmail", "config", "usage"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Site from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of config
        if self.config:
            _dict['config'] = self.config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['usage'] = self.usage.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Site from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "siteId": obj.get("siteId"),
            "title": obj.get("title"),
            "status": obj.get("status"),
            "permission": obj.get("permission"),
            "roles": obj.get("roles"),
            "permissions": obj.get("permissions"),
            "uploadEmail": obj.get("uploadEmail"),
            "config": SiteConfig.from_dict(obj["config"]) if obj.get("config") is not None else None,
            "usage": SiteUsage.from_dict(obj["usage"]) if obj.get("usage") is not None else None
        })
        return _obj


