# coding: utf-8

"""
    FormKiQ API JWT

    FormKiQ API: Document Management Platform API using OAuth(JWT) Authentication  You can find out more about FormKiQ at [https://formkiq.com](http://formkiq.com).  ## Introduction  FormKiQ is an API-first (head-less), battle-tested document management API. The FormKiQ API provides all the API endpoints to build your Perfect Document Management Platform.  FormKiQ API was built on top of [OpenAPI specification](https://www.openapis.org), so it is easy to use the API spec file with any application that supports the OpenAPI specification.  Open API OAuth Specification - https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-jwt.yaml  Open API IAM Specification - https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-iam.yaml  ## Authentication FormKiQ offers three forms of authentication:   - OAuth(JWT)   - AWS IAM   - API Key

    The version of the OpenAPI document: 1.19.0
    Contact: support@formkiq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from formkiq_client.models.workflow_step_condition_operator import WorkflowStepConditionOperator
from formkiq_client.models.workflow_step_condition_source import WorkflowStepConditionSource
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WorkflowStepConditionCriterion(BaseModel):
    """
    A single criterion used to evaluate whether a workflow condition matches.  A criterion compares a document-derived source value against one or more provided values using the specified operator.  Supported sources include: - document attributes - document attribute value comparisons - document content type - document path  Typical examples: - attribute `status` equals `approved` - attribute `amount` greater than `1000` - attribute `invoiceTotal` equals attribute `approvedTotal` - attribute `invoiceTotal` equals the sum of attribute `lineItemAmount` - content type equals `application/pdf` - path contains `/invoices/`  Use the appropriate typed value field for the comparison: - `stringValue` for string comparisons - `numberValue` for numeric comparisons - `booleanValue` for boolean comparisons - `stringValues` for multi-value comparisons such as `IN` and `NOT_IN`  Literal value fields should be omitted when `source` is an attribute value comparison. 
    """ # noqa: E501
    source: WorkflowStepConditionSource
    operator: WorkflowStepConditionOperator
    string_value: Optional[StrictStr] = Field(default=None, description="String comparison value", alias="stringValue")
    number_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Numeric comparison value", alias="numberValue")
    boolean_value: Optional[StrictBool] = Field(default=None, description="Boolean comparison value", alias="booleanValue")
    string_values: Optional[List[StrictStr]] = Field(default=None, description="String values used for IN or NOT_IN comparisons", alias="stringValues")
    __properties: ClassVar[List[str]] = ["source", "operator", "stringValue", "numberValue", "booleanValue", "stringValues"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkflowStepConditionCriterion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of source
        if self.source:
            _dict['source'] = self.source.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkflowStepConditionCriterion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "source": WorkflowStepConditionSource.from_dict(obj["source"]) if obj.get("source") is not None else None,
            "operator": obj.get("operator"),
            "stringValue": obj.get("stringValue"),
            "numberValue": obj.get("numberValue"),
            "booleanValue": obj.get("booleanValue"),
            "stringValues": obj.get("stringValues")
        })
        return _obj


