# coding: utf-8

"""
    FormKiQ HTTP API

    Formkiq API: Document Management Platform API using JWT Authentication  # noqa: E501

    The version of the OpenAPI document: 1.12.0
    Contact: support@formkiq.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.set_document_version_request import SetDocumentVersionRequest
from openapi_client import configuration


class TestSetDocumentVersionRequest(unittest.TestCase):
    """SetDocumentVersionRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
