# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from formkiq_client.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    VERSION = "/version"
    SITES = "/sites"
    CONFIGURATION = "/configuration"
    CONFIGURATION_API_KEYS = "/configuration/apiKeys"
    CONFIGURATION_API_KEYS_API_KEY = "/configuration/apiKeys/{apiKey}"
    DOCUMENTS = "/documents"
    DOCUMENTS_DOCUMENT_ID = "/documents/{documentId}"
    DOCUMENTS_DOCUMENT_ID_CONTENT = "/documents/{documentId}/content"
    DOCUMENTS_DOCUMENT_ID_TAGS = "/documents/{documentId}/tags"
    DOCUMENTS_DOCUMENT_ID_TAGS_TAG_KEY = "/documents/{documentId}/tags/{tagKey}"
    DOCUMENTS_DOCUMENT_ID_TAGS_TAG_KEY_TAG_VALUE = "/documents/{documentId}/tags/{tagKey}/{tagValue}"
    DOCUMENTS_TAGS = "/documents/tags"
    DOCUMENTS_DOCUMENT_ID_URL = "/documents/{documentId}/url"
    DOCUMENTS_UPLOAD = "/documents/upload"
    DOCUMENTS_DOCUMENT_ID_UPLOAD = "/documents/{documentId}/upload"
    DOCUMENTS_COMPRESS = "/documents/compress"
    SEARCH = "/search"
    SEARCH_FULLTEXT = "/searchFulltext"
    QUERY_FULLTEXT = "/queryFulltext"
    DOCUMENTS_DOCUMENT_ID_ACTIONS = "/documents/{documentId}/actions"
    DOCUMENTS_DOCUMENT_ID_OCR = "/documents/{documentId}/ocr"
    DOCUMENTS_DOCUMENT_ID_VERSIONS = "/documents/{documentId}/versions"
    DOCUMENTS_DOCUMENT_ID_VERSIONS_VERSION_KEY = "/documents/{documentId}/versions/{versionKey}"
    FOLDERS = "/folders"
    FOLDERS_INDEX_KEY = "/folders/{indexKey}"
    SHARES = "/shares"
    SHARES_FOLDERS_INDEX_KEY = "/shares/folders/{indexKey}"
    SHARES_SHARE_KEY = "/shares/{shareKey}"
    TAG_SCHEMAS = "/tagSchemas"
    TAG_SCHEMAS_TAG_SCHEMA_ID = "/tagSchemas/{tagSchemaId}"
    DOCUMENTS_DOCUMENT_ID_ANTIVIRUS = "/documents/{documentId}/antivirus"
    DOCUMENTS_DOCUMENT_ID_FULLTEXT = "/documents/{documentId}/fulltext"
    DOCUMENTS_DOCUMENT_ID_FULLTEXT_TAGS_TAG_KEY = "/documents/{documentId}/fulltext/tags/{tagKey}"
    DOCUMENTS_DOCUMENT_ID_FULLTEXT_TAGS_TAG_KEY_TAG_VALUE = "/documents/{documentId}/fulltext/tags/{tagKey}/{tagValue}"
    DOCUMENTS_DOCUMENT_ID_SYNCS = "/documents/{documentId}/syncs"
    PUBLIC_DOCUMENTS = "/public/documents"
    PUBLIC_WEBHOOKS_WEBHOOKS = "/public/webhooks/{webhooks+}"
    PRIVATE_WEBHOOKS_WEBHOOKS = "/private/webhooks/{webhooks+}"
    WEBHOOKS = "/webhooks"
    WEBHOOKS_WEBHOOK_ID = "/webhooks/{webhookId}"
    WEBHOOKS_WEBHOOK_ID_TAGS = "/webhooks/{webhookId}/tags"
    ONLYOFFICE_DOCUMENT_ID_EDIT = "/onlyoffice/{documentId}/edit"
    ONLYOFFICE_NEW = "/onlyoffice/new"
    ONLYOFFICE_DOCUMENT_ID_SAVE = "/onlyoffice/{documentId}/save"
    INDICES_INDEX_TYPE_MOVE = "/indices/{indexType}/move"
    INDICES_INDEX_TYPE_INDEX_KEY = "/indices/{indexType}/{indexKey}"
    INDICES_SEARCH = "/indices/search"
    ESIGNATURE_DOCUSIGN_DOCUMENT_ID = "/esignature/docusign/{documentId}"
    ESIGNATURE_DOCUSIGN_CONFIG = "/esignature/docusign/config"
    ESIGNATURE_DOCUSIGN_EVENTS = "/esignature/docusign/events"
